# Generated by Django 2.1.2 on 2019-01-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile_1',
        ),
    ]
