# Generated by Django 2.1.2 on 2019-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_auto_20190120_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'profile_2',
            },
        ),
        migrations.AlterModelOptions(
            name='profile_1',
            options={'verbose_name_plural': 'profile_1'},
        ),
    ]
