# Generated by Django 2.1.2 on 2019-01-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grad_institute',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='grad_year',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
