# Generated by Django 2.1.2 on 2019-01-07 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_executive', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('educational_institue', models.CharField(max_length=210)),
                ('hsc_year', models.CharField(max_length=20)),
            ],
        ),
    ]
